### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by KurtPachinger** [KurtPachinger/mpos-precept#1]
## enhancement
- [x] update wiki documentation
- [x] depth:
  - [x] honor z-index
  - [x] allow arc/radial
    - [x] ~~arc smooth: displace map, or shader positions, or [SkinnedMesh](https://twitter.com/Cody_J_Bennett/status/1621211388344410113)~~, ~~IK chain~~
  - [x] ux: ~~highlight, and arc front to uv or origin~~
- [x] types:
  - [x] store node in userData
  - [x] allow: box, html-to-image, CSS3DRenderer
    - [x] manual class hints
    - [x] [mixed-content: ~~test internal resource~~](https://github.com/KurtPachinger/mpos-precept/issues/1#issuecomment-1564589277)
    - [x] html-to-image
      - [x] InstancedMesh with texture atlas
        - [ ] flag duplicate img src to share uv, with lazy re-index if src changes (see cache, differ)
        - [x] texture pack size relative to type+priority
      - [x] ~~limit dimensions~~ (track, crash) -- `1>n<2048,3840,4096`
      - [x] [clone node into dummy ShadowDom div, to avoid un-set class hierarchy?](https://codesandbox.io/p/sandbox/mbox-two-fh82gw)
  - [x] url input
    - [ ] update resets size from non-unset (mp-offscreen)
    - [x] load url: use FileLoader (needs address populated once? )
  - [x] class `.loader`: expose to THREE (i.e. SVGLoader, AudioLoader, arbitrary xml) ~~enable-vr~~
    - [x] ~~FontLoader: match h2, p, svg text?~~
    - [x]  ~~share generic path/hole pattern (SVGLoader, FontLoader, OpenCV)~~
    - [ ] class tools: gan-3d, gan-train-walk, gan-txt2pic
  - [x] progressive `poster`: convert text to path (cv.kmeans, cv.inRange, cv.findContours). For example, `h2.mp-loader` would output like SVGLoader. ([gzip](https://stackoverflow.com/questions/9468511/how-can-i-estimate-the-size-of-my-gzipped-script), [docker](https://docs.opencv.org/4.x/d4/da1/tutorial_js_setup.html))
    - [x] hierarchy holes
    - [x] ~~limit toPng size~~
  - [x] comment callback: stub for xml, php
- [x] update:
  - [x] prefer viewport
  - [x] live plot: IntersectionObserver
  - [x] dom: soft update
    - [x] shader
    - [x] other/native/loader
    - [x] scrollY
    - [x] unset
    - [x] use of transforms(paint): atlas[0,½]
    - [x] callback to repeat queue (animate)
      - [x] clearTimeout: duplicate loop in GUI and ux 
      - [x] fast frame, inPolar==4: parent css transform matrix not ready
      - [x] loop busy: frame 0 adds lazy-loaded mesh (loader, fitting)
      - [x] reduce: compare bound and css, (with ux i/o)
    - [x] update(trim): query visible (~~Observer~~)
    - [x] ~~MutationObserver~~ ~~one MutationObserver instead of multiple IntersectionObserver~~
    - [ ] class `mp-diffs` force element to re-render once (similar to `mp-native`)
  - [x] grade: [keyed refs, dispose, weakmap](https://github.com/KurtPachinger/mpos-precept/issues/4#issuecomment-2629330223)
  - [ ] MouseEvent: click targets, bubble/capture phase, vr patterns like a-frame fuse
- [x] HTML generator: populate ~~from seed~~ (section,article,h2,img,ul,embed)
- [x] ~~web3 hooks: node atlas matrix `[a1,b2]::[a2,b1]` use GAN for... spatial cross?~~
- [x] demos: game map (FPS, racetrack), advanced CSS chains, GUI menu, CMS for test suites
- [ ] scale factor
- [x] performance:
  - [x] verify renderer.info releases, variable scope...
  - [x] DevTools: `update` may retain refs to DOM Nodes
  - [x] ~~frustum cull~~
  - [x] again try manual matrix update
  - [x] selector body is much slower than body>main (texture atlas time)
  - [ ] OffscreenCanvas / copyTextureToTexture

## bug
- [x] expose `mpos` to window on init:
- [x] dom loop:
  - [x] return group
  - [x] grade.hardmax from viewport
  - [x] siblings increment depth
  - [x] NodeIterator: should wrap orphan #text nodes so interactive count is consistent, and to save time.
  - [x] inPolar control: PREVIOUS|CONTAINS
  - [x] text node wrap: test clauses for `orphan_list` and `orphan_semantic`
  - [x] ~~element nested in tags deep/ignored/empty (solved by manual class hints)~~
  - [x] hide child for poster texture (if poster > poster is allowed... i.e. for background textures)
- [x] CSS3D clones and order 
  - [x] transforms: css matrix (from parents) to `struct.opts` for `box.opts`
  - [x] ~~hooks -- details only opens programmatically (OrbitControls preventDefault?)~~
  - [x] [performance: on zoom, CSS3D degrades from vector to raster. Then emoji becomes garbled character (DOM clone AND original). Even in another tab... but after away, memory resets. `MAX_TEXTURE_SIZE`](https://github.com/KurtPachinger/mpos-precept/issues/1#issuecomment-1563031479)
  - [x] ComputedStyle -- elements need module-specific css, parent element(s) for relational scale... so html-to-image
  - [x] inherit modular: stub DOM tree, or poll ancestor styles [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range/commonAncestorContainer)
  - [x] mask z-depth ([threeml](https://discourse.threejs.org/t/css3drednerer-object/36464), [48702](https://discourse.threejs.org/t/problem-with-interaction-when-merging-webglrenderer-css3drenderer/48702?page=2), [HTMLMesh](https://twitter.com/BlurSpline/status/1487455546399617028?lang=en))
- [x] gui arc: lost anchor 
- [x] Controls: 
  - [x] preventing clicks
  - [x] no pinch/zoom on mobile
- [x] update quirks:
  - [x] depth: body, value <2
  - [x] object.position.y += document.scrollTop
  - [x] update: `rect.obj<Mesh>` is stale?
  - [x] ~~little skinny details div (mat=self)~~
  - [x] object: no url leaves skinny div, blocks form
  - [x] details[closed] > details (hidden, inPolar 2): 
      - [x] unset: transform origin wrong
      - [x] unset: closes itself on mobile
  - [x] inPolar==4: rect.add only fires on hard update
  - [x] getComputedStyle: css background (0,0,0,0)
  - [x] object embed: wrong position, double
  - [x] stress test: settings (inPolar?) may expect rect.el, in race from dat.GUI
  - [x] hard-update: abort concurrent dom()
  - [x] update: verify still needs Promise and two distinct dataIdx of move/trim
  - [x] ~~data-idx: preserve uid next NodeIterator~~
  - [x] atlas: reverse-loop not user-friendly
  - [x] ~~frame: values above 60 have lower FPS~~
- [x] materials (atlas)
  - [x] atlas: use strip, not square
  - [x] ~~toSvg errors~~ (try/catch for missing img.src, without fallback)
  - [x] ref lookup (bound, css attribute): [extend](https://github.com/KurtPachinger/mpos-precept/issues/1#issuecomment-1627706400)?
      - [x] inPolar: use rect.bound
      - [x] rect.css: arc group lost initial rotation... aside#transform lost initial rotation
      - [x] onscroll reflow: update render doesn't queue box, without frame
      - [x] edge cases: stretch/skew OO, faux-bold
      - [x] defer css > getComputedStyle() for rect.ux.o<1
      - [x] queue (from Observer per inPolar) has checks (backgroundColor,atlas) which could have better default support
      - [x] atlas (on mobile): OffscreenCanvas.clearRect() breaks alpha on frame, after mpos.dom() is recalled
  - [x] overflow: 
    - [x] details[closed] children do not update position
    - [ ] checkVisibility breaks on iOS
    - [ ] scroll is visible
- [x] loader: if page is cached and refreshed, initial update loop ( OpenCV, SVGLoader ) becomes very slow. Also other should use Promise.
- [x] improve raycast

**Comment by KurtPachinger** [comment]
### crash, display and memory

`THREE.Color: Unknown color transparent`
`THREE.Color: Alpha component of rgba(128, 128, 128, 0.125) will be ignored.`
`Too many active WebGL contexts. Oldest context will be lost.`
`THREE.WebGLRenderer: Context Lost.`
`THREE.WebGLRenderer: Context Restored.`

- [x] After a reboot, in a new browser window, I see a reproducable bug.
The entire browser flashes black, and then the canvas background is black.
It occurs when I update CodeSandbox (i.e. CTRL+X to move a console.log(), or backspace).
When I set the black canvas opacity to 0.9999999 (or lower), OrbitControls does not respond.

- [x] ~~Also, there is a mesh rectangle of widely varying dimensions added to my scene. 
It is >300% the size of my viewport, and very wide or tall. It is always at different y angles.
I am using CSS3DRenderer.~~ arc

**Comment by KurtPachinger** [comment]
## media bias: mime/type
| mixed-content | CSS3D `.mp-native` | toSvg `.mp-poster` | FileLoader `.mp-loader` |
| --- | --- | --- | --- |
| * | `100%` ~~`events`~~ `cors` | `<512` | `#comment` |
| * . * | `htm` `pdf` | `jpg` `txt` | `xml` |
| `model-viewer` `a-scene` `babylon` `three-d-viewer` `#stl_cont` `#root` `.sketchfab-embed-wrapper` `StandardReality` | ✓ |||
| iframe, object, embed | ✓ |||
| svg | ✓ || `SVGLoader` ~~`text`~~ |
| canvas || ✓ ||
| audio | `controls` || `AudioLoader` |
| `Lena.mp-loader` ||| `OpenCV` |

**Comment by KurtPachinger** [comment]
## module import/export
- [x] scope: unique css
- [x] DOM inject: three, css3d, atlas, address
- [x] ~~CSS3D: z-index 99~~
- [x] dat.GUI: default selector
- [x]  pass scene to `init(?)` , as opposed to `Group.selector > userData > grade`
  ```js
  init ( renderer, scene, camera ) {
  if ( renderer && scene && camera ) {
  // DON'T: render, resize, update camera, helpers
  // DO:
    // renderer.domElement
    // - append CSS3D
    // - classList.add `mp-block`
    // reference
    // - add to scene, dispose
    // - update(grade), events
  } 
  ```
- [x] separate mp CSS from test page

### best practice & accessibility
- [x] obscure resources "below the fold": ~~inertia, FOV, perspective, distance~~
- [x] ~~screen-read reference node innerHTML~~
- [x] ~~form clone data authenticity~~

**Comment by KurtPachinger** [comment]
## frame update: box models (shortlist)

- [x] reference `maxEls` to batch-process [idx-queue]
- [x] make promise `atlas` > `transform` external to `dom`

### HARD-REFRESH: MutationObserver
Rebuild all nodes, excluding eligible/active forms or videos.
- while ( el[data-idx] !== grade.rects[data-idx] ) 
  - attributes { inPolar, xyz, width, height }
  - update or add: rect.atlas || atlas++

### SOFT-REFRESH: IntersectionObserver
Focus update within viewport, and minimize reflow (zero-height, lazy-loaded, triggered...).
- update or add: from grade.rects[data-idx] 
  - { inPolar && mat } ==> ( rect.atlas || atlas++ )

![update](https://github.com/KurtPachinger/mpos-precept/assets/48163461/6ba9b972-86b4-4890-a3a6-24612b723530)
use cases: scroll, resize, live DOM, accordion/gallery

**Comment by KurtPachinger** [comment]
## frame update: css/transforms (shortlist)
An `update` should:
- reduce the `queue`: visibility
- cache refs on `frame`: bound, css
  - refs used in: `box`, `css`, `raycast`, `event`
- prioritize `ux`: native, active

|done|queue priority|attribute|usage|
|--|--|:--|:--|
|...|1|:pseudo|after, before, hover, focus|
|✓|3|animation||
|✓||background|color|
|||border|color, width|
||2|opacity||
||1|overflow|scroll|
|✓||position|fixed|
|✓|3|transform|matrix, origin, rotate, scale|
|✓|3|transition||
||2|visibility||
|✓||z-index|integer|

*outliers: deep tree, filetype.gif, canvas, loader, hidden iframe

**Comment by KurtPachinger** [comment]
## html-to-canvas

https://codesandbox.io/p/sandbox/mbox-two-fh82gw
**Issue:** draw canvas from HTML element... **styled** node, **fits** box to edge un-transformed, **offscreen** from DOM.

1. get/set box size (un-transformed) from toCanvas (...then reduce texture scale)
2. set box parent/child in THREE to
    - accumulate transforms and 
    - reduce updates and 
    - maintain relationship access

**Comment by KurtPachinger** [comment]
## [synthetic event dispatch](https://github.com/KurtPachinger/mpos-precept/wiki/Process-Flow#sync-frame)

### RAYCAST:
- raycaster distance is the average of width/height, assuming scale pixels 1:1
- ? jumps from 0.001 to 0.6 at leftmost edge
- gui panel on right drags horizontal (w dev panel open) offset
- ++ cache filter removes all the targets once page settles
- uv/xy
  - ++ flip, negate
  - ++ specific click is 1 element height too high (pageX, screenX)
  - ++ EVENT click xy using coords from unset uv
  - EVENT BoundingClientRect from live element
- even a 1px border style change effectively disables expectations
### MOUSE EVENT:
- slight movement may be lost, to precision within 3d context
- need thicker click-targets, i.e. multi-sample
- raycast replaces the event too soon, or window jank loses event (with controls enablePanning)
- synthetic depth type "native": disable controls pan if NodeIterator finds (primary) event.target (by data-idx)
### SYNTHETIC DISPATCH:
- details :pseudo arrow does not accept/propagate synthetic clicks events
- mousedown:
  - position used from caller (event+raycast) on target (native form slider)... without offset distance 
  - ...synthetic dispatch to "original" callee event needs difference (and skew?)
- z-depth/zIndex and bubble/capture
  - quirks of recreation propagation (box, auto, inheritance)
  - z-fight: +0.001 or !depthWrite
    - many child elements report 'auto' zIndex depth
    - ... and potentially a specified zIndex
    - ... and inherit
    - commonly(?) mesh adds +0.001 to simulate zIndex, and fix z-fight
    - ...with raycast depth allowing (and shadow)

https://github.com/KurtPachinger/mpos-precept/issues/1#issuecomment-2634751634

**Comment by KurtPachinger** [comment]
Nominal Time Partition: real deviation
Frame Sync and Feedback: render may invoke targets to collocate
sPhase and sFence


<details>
<summary>sketch</summary>

![Frame Sync](https://github.com/user-attachments/assets/8183e06f-97e9-410c-9beb-bd306873fe5b)
![Time Subset](https://github.com/user-attachments/assets/e0f1f5a1-0ff9-4558-9e03-9a1780e429a6)
![State Diagram](https://github.com/user-attachments/assets/fab9c314-2485-49d4-a294-017ea17a343b)
![Time Gate/Ramp](https://github.com/user-attachments/assets/30e32486-8777-444b-b76d-4942436af7e4)

</details>

<details>
<summary>notes</summary>

## FPS and Performance Variables

### delta: overwrites
- &gt; 30: frame once
- &lt; 30: binary no

### quality: overwrites
- 0.5: frame time half of expected
- 1.0: frame time exactly expected
- 2.0: frame took twice as long

## FPS Delta Range

### observation 1
1. focus small: at most (1.3-.5) gap to .3
2. average media: (.15 : .4) 
2. full-page active: low (.01 : .08)

### observation 2
1. delay > 160 : quality usually .999 (given ample time for updates)
2. delay 160 > 40 : quality declines to .40 +/- .10 (fluctuate more widely)
3. delay 5: quality 0.05
   - current quality threshold forces range (0.8 : 1.0) pixelRatio (rect.ux.o)

---

## Quality Checks: Delta + Performance Calibration

- garbage collection spikes
- render loop: purpose is to keep it smooth
  - how is delta updated, versus how Stats reports FPS?
  - only updates texture and wiggles view
- update: without skipping a frame /unset
  - texture atlas
  - transforms
  - ux events transient
- loader: video or opencv could swap low-quality sources


---


```javascript
intFPS/intDelta	product		complement			difference	align (0.033/2)		1/
===		===		===		===		===		===
0.033/0.078	0.423		1-0.423		0.577		-0.045 *	.045/.016	2.701	0.355
0.033/0.146	0.226		1-0.226		0.774		-0.113		.113/.016 	6.782	0.141
		0.649										9.483	0.497
												/10	*2
intDelta/intFPS	product		reciprocal
===		===		===		===
0.078/0.033	2.363x		1/2.363		0.423		0.045 *		-
0.146/0.033	4.424x		1/4.424		0.226		0.113		-


0.033*1000 = 33 milliseconds (...5, 150, 300)


delay/elapsed
===		===		===		===
5/80		0.0625
5/130		0.0384

80/5		16x
130/5		26x

delay/interval
===		===		===		===


==[[9.483 x 0.0625 = 0.5926]]

//
// RESULT (scratch)

1 / ( ( intDelta - intFPS ) / ( intFPS / 2 ) )
1 / ( (        0.045      ) / (    0.016   ) )			2.8
1 / (                     2.701              )  =  0.3702


( 5/80 )
 0.0625


t1 = ( 0.3702 * 1.5 ) = .5553
t2 = ( 0.3702 ) + |(0.5 - 0.0625 )|

//
// RESULT (transcribe)

const intProduct = 1 / ( ( intDelta - intFPS ) / ( intFPS / 2 ) )
const nomProduct = Math.abs( 0.5 - ( delay / elapsed ) )
const weightedAverage = intProduct + nomProduct

//
//const intProduct = (1 / ((time.intDelta - time.intFPS) / (time.intFPS / 2))) * 1.5
//const intProduct = 1 / ((time.intDelta - time.intFPS) / (time.intFPS / 2))

//sPhase
//sFence

```

</details>
